### ISSUE TITLE
Could not resolve host: hostname-svc.default (Failed to watch *v1alpha3.DestinationRule:)

### ISSUE THREAD

**Issue by EnfangCui** [kubeedge/edgemesh#31]
OS: ubuntu 18.04.4 LTS
KubeEdge version: v1.7.1
EdgeMesh version: v1.7.0
K8S version:1.9.0

Problem:
``` 
root@edgenode:~# curl hostname-svc.default:12345 -v
* Rebuilt URL to: hostname-svc.default:12345/
* Could not resolve host: hostname-svc.default
* Closing connection 0
curl: (6) Could not resolve host: hostname-svc.default
```
When I do this: docker logs -f  "edgemesh agent container id"
It returns an error "Failed to watch *v1alpha3.DestinationRule" like follows:
```
root@edgenode:~# docker logs -f 2b35df37d825
2021/08/13 02:07:31 INFO: Install client plugin, protocol: rest
2021/08/13 02:07:31 INFO: Installed service discovery plugin: edge
I0813 02:07:31.181969       1 server.go:54] Version: v1.7.1-9+2b655fcbc51f38
I0813 02:07:31.181988       1 server.go:88] [1] New informers manager
I0813 02:07:31.182448       1 server.go:95] [2] Register beehive modules
I0813 02:07:31.182722       1 module.go:34] Module edgedns registered successfully
I0813 02:07:31.190298       1 module.go:34] Module edgeproxy registered successfully
W0813 02:07:31.190381       1 module.go:37] Module edgegateway is disabled, do not register
I0813 02:07:31.190438       1 privkey.go:34] Private key does not exist, generate a new one
I0813 02:07:31.266883       1 module.go:34] Module tunnelagent registered successfully
I0813 02:07:31.267035       1 server.go:104] [3] Install go-chassis plugins
I0813 02:07:31.267146       1 log.go:181] DEBUG: Installed strategy plugin: [RoundRobin].
I0813 02:07:31.267195       1 log.go:181] DEBUG: Installed strategy plugin: [Random].
I0813 02:07:31.267222       1 log.go:181] DEBUG: Installed strategy plugin: [ConsistentHash].
I0813 02:07:31.267263       1 log.go:181] DEBUG: ConfigurationFactory Initiated
I0813 02:07:31.267291       1 log.go:181] INFO: Configuration files: []
I0813 02:07:31.267334       1 log.go:181] WARN: empty configurtion from [FileSource]
I0813 02:07:31.267371       1 log.go:181] INFO: invoke dynamic handler:FileSource
I0813 02:07:31.267410       1 log.go:181] INFO: archaius init success
I0813 02:07:31.267444       1 server.go:109] [4] Start informers manager
I0813 02:07:31.268402       1 log.go:181] INFO: create new watcher
E0813 02:07:31.294654       1 reflector.go:127] /code/common/informers/informers.go:87: Failed to watch *v1alpha3.DestinationRule: failed to list *v1alpha3.DestinationRule: no kind "DestinationrulList" is registered for version "networking.istio.io/v1alpha3" in scheme "istio.io/client-go/pkg/clientset/versioned/scheme/register.gen.go:30"
E0813 02:07:31.294784       1 reflector.go:127] istio.io/client-go/pkg/informers/externalversions/factory.gen.go:116: Failed to watch *v1alpha3.DestinationRule: failed to list *v1alpha3.DestinationRule: no kind "DestinationrulList" is registered for version "networking.istio.io/v1alpha3" in scheme "istio.io/client-go/pkg/clientset/versioned/scheme/register.gen.go:30"
E0813 02:07:32.327858       1 reflector.go:127] istio.io/client-go/pkg/informers/externalversions/factory.gen.go:116: Failed to watch *v1alpha3.DestinationRule: failed to list *v1alpha3.DestinationRule: no kind "DestinationrulList" is registered for version "networking.istio.io/v1alpha3" in scheme "istio.io/client-go/pkg/clientset/versioned/scheme/register.gen.go:30"
```

My yaml : kubectl apply -f examples/hostname.yaml
``` yaml
apiVersion: v1
kind: Pod
metadata:
  name: hostname-edge
  namespace: default
  labels:
    app: hostname-edge
spec:
  nodeName: edgenode
  containers:
    - name: hostname
      image: k8s.gcr.io/serve_hostname:latest
      imagePullPolicy: IfNotPresent
      ports:
        - containerPort: 9376
          hostPort: 9376
---
apiVersion: v1
kind: Service
metadata:
  name: hostname-svc
  namespace: default
spec:
  selector:
    app: hostname-edge
  ports:
    - name: http-0
      port: 12345
      protocol: TCP
      targetPort: 9376
```

curl 127.0.0.1:10550/api/v1/services on edgenode
```
root@edgenode:~# curl 127.0.0.1:10550/api/v1/services
{"apiVersion":"v1","items":[{"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"kubectl.kubernetes.io/last-applied-configuration":"{\"apiVersion\":\"v1\",\"kind\":\"Service\",\"metadata\":{\"annotations\":{},\"name\":\"argo-server\",\"namespace\":\"argo\"},\"spec\":{\"ports\":[{\"name\":\"web\",\"port\":2746,\"targetPort\":2746}],\"selector\":{\"app\":\"argo-server\"}}}\n"},"creationTimestamp":"2021-07-30T06:47:54Z","managedFields":[{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:annotations":{".":{},"f:kubectl.kubernetes.io/last-applied-configuration":{}}},"f:spec":{"f:ports":{".":{},"k:{\"port\":2746,\"protocol\":\"TCP\"}":{".":{},"f:name":{},"f:port":{},"f:protocol":{},"f:targetPort":{}}},"f:selector":{".":{},"f:app":{}},"f:sessionAffinity":{},"f:type":{}}},"manager":"kubectl-client-side-apply","operation":"Update","time":"2021-07-30T06:47:54Z"}],"name":"argo-server","namespace":"argo","resourceVersion":"41590887","selfLink":"argo/services/argo-server","uid":"85953948-4514-4973-a614-c035133472ce"},"spec":{"clusterIP":"10.102.174.236",
......
```

**Comment by Poorunga** [comment]
I guess the crd of destinationRule is not installed. Check it like this:
```
[root~dev-node ~]# kubectl get crds | grep destinationrules
destinationrules.networking.istio.io           2021-07-19T07:33:06Z
```

If you can't see anything, you can try this command:
```
kubectl apply -f build/crds/istio/destinationrule-crd.yaml
```

Finally, you can redeploy edgemesh-agent and tell me if the problem is solved :)

**Comment by EnfangCui** [comment]
> I guess the crd of destinationRule is not installed. 
> ```
> kubectl apply -f build/crds/istio/destinationrule-crd.yaml
> ```

@Poorunga Thank you very much. This problem has been solved, but a new problem has arisen

```
W0813 06:55:34.566589       1 dns.go:57] resolve dns: get from real dns
W0813 06:55:34.566911       1 dns.go:57] resolve dns: get from real dns
W0813 06:55:34.567222       1 dns.go:57] resolve dns: get from real dns
E0813 06:55:34.573293       1 dns.go:112] service reverse clusterIP error: service "edgenode" not found
W0813 06:55:34.573305       1 dns.go:57] resolve dns: get from real dns
W0813 06:55:34.574816       1 dns.go:57] resolve dns: get from real dns
E0813 06:55:36.183560       1 dns.go:112] service reverse clusterIP error: service "ghcr" not found
W0813 06:55:36.183577       1 dns.go:57] resolve dns: get from real dns
W0813 06:55:36.183931       1 dns.go:57] resolve dns: get from real dns
E0813 06:55:36.582169       1 tunnel.go:22] Failed to get tunnel server addr
W0813 06:55:39.118162       1 dns.go:57] resolve dns: get from real dns
E0813 06:55:41.582286       1 tunnel.go:22] Failed to get tunnel server addr
W0813 06:55:44.368097       1 dns.go:57] resolve dns: get from real dns
W0813 06:55:44.575143       1 dns.go:57] resolve dns: get from real dns
I0813 06:55:46.184474       1 dns.go:115] dns server parse hostname-svc.default ip 10.106.128.216
W0813 06:55:46.184704       1 dns.go:57] resolve dns: get from real dns
I0813 06:55:46.244630       1 proxy.go:38] clusterIP: 10.106.128.216, servicePort: 12345
W0813 06:55:46.244903       1 util.go:21] DestinationRule "default.hostname-svc" not found, use default strategy [RoundRobin] from config file
I0813 06:55:46.244916       1 log.go:181] DEBUG: add [2] handlers for chain [http]
I0813 06:55:46.244991       1 log.go:181] INFO: Create client for rest:hostname-svc.default.svc.cluster.local:12345:edgenode:192.168.0.12:9376
I0813 06:55:46.245207       1 log.go:181] ERROR: Call got Error, err [[Get "http://edgenode:192.168.0.12:9376/": dial tcp: lookup edgenode:192.168.0.12: no such host]]
W0813 06:55:46.245412       1 http.go:61] read http request EOF
E0813 06:55:46.582416       1 tunnel.go:22] Failed to get tunnel server addr
W0813 06:55:49.575472       1 dns.go:57] resolve dns: get from real dns
E0813 06:55:51.582517       1 tunnel.go:22] Failed to get tunnel server addr
E0813 06:55:54.575390       1 dns.go:112] service reverse clusterIP error: service "edgenode" not found
```

**Comment by Poorunga** [comment]
Are you using the code from the main branch?

**Comment by vcozzolino** [comment]
I have the same problem. I'm using the image kubeedge/edgemesh:v1.7.0 and I also installed the destinarionrules crd. However, the problem is still there as I can see in my gateway logs the following:

```
E0813 08:31:30.618592       1 reflector.go:127] istio.io/client-go/pkg/informers/externalversions/factory.gen.go:116: Failed to watch *v1alpha3.DestinationRule: failed to list *v1alpha3.DestinationRule: no kind "DestinationrulList" is registered for version "networking.istio.io/v1alpha3" in scheme "istio.io/client-go/pkg/clientset/versioned/scheme/register.gen.go:30"
I0813 08:31:35.852720       1 trace.go:205] Trace[1653888543]: "Reflector ListAndWatch" name:istio.io/client-go/pkg/informers/externalversions/factory.gen.go:116 (13-Aug-2021 08:31:25.851) (total time: 10001ms):
Trace[1653888543]: [10.001505598s] [10.001505598s] END
```

If you carefully read the log, you can see that it's looking for a kind named "DestinationrulList". Isn't there a typo? Shouldn't it be "Destinationrul**e**List"?

**Comment by EnfangCui** [comment]
> Are you using the code from the main branch? The latest main branch needs to deploy edgemesh-server, but this part of the content has not been updated to the readme. You can refer pr: #29.
> 
> It is recommended that you switch to release-1.7.0, refer to: https://github.com/kubeedge/edgemesh/tree/release-1.7 and use this image: kubeedge/edgemesh:v1.7.0.

Thank you very much. I switched to the release-1.7.0, and the problem was solved. I used main branch before.

**Comment by EnfangCui** [comment]
1

**Comment by Poorunga** [comment]
> If you carefully read the log, you can see that it's looking for a kind named "DestinationrulList". Isn't there a typo? Shouldn't it be "Destinationrul**e**List"?

I don't think it is a typo problem.

Perhaps you should first check if the list-watch capability of edgecore is working properly, try it:

**Comment by Poorunga** [comment]
> If you carefully read the log, you can see that it's looking for a kind named "DestinationrulList". Isn't there a typo? Shouldn't it be "Destinationrul**e**List"?

 
@vcozzolino  I don't think it is a typo problem.

Perhaps you should first check if the list-watch capability of edgecore is working properly, try it:
```
$ curl 127.0.0.1:10550/api/v1/services
{"apiVersion":"v1","items":[{"apiVersion":"v1","kind":"Service","metadata":{"creationTimestamp":"2021-04-14T06:30:05Z","labels":{"component":"apiserver","provider":"kubernetes"},"name":"kubernetes","namespace":"default","resourceVersion":"147","selfLink":"default/services/kubernetes","uid":"55eeebea-08cf-4d1a-8b04-e85f8ae112a9"},"spec":{"clusterIP":"10.96.0.1","ports":[{"name":"https","port":443,"protocol":"TCP","targetPort":6443}],"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}},{"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"prometheus.io/port":"9153","prometheus.io/scrape":"true"},"creationTimestamp":"2021-04-14T06:30:07Z","labels":{"k8s-app":"kube-dns","kubernetes.io/cluster-service":"true","kubernetes.io/name":"KubeDNS"},"name":"kube-dns","namespace":"kube-system","resourceVersion":"203","selfLink":"kube-system/services/kube-dns","uid":"c221ac20-cbfa-406b-812a-c44b9d82d6dc"},"spec":{"clusterIP":"10.96.0.10","ports":[{"name":"dns","port":53,"protocol":"UDP","targetPort":53},{"name":"dns-tcp","port":53,"protocol":"TCP","targetPort":53},{"name":"metrics","port":9153,"protocol":"TCP","targetPort":9153}],"selector":{"k8s-app":"kube-dns"},"sessionAffinity":"None","type":"ClusterIP"},"status":{"loadBalancer":{}}}],"kind":"ServiceList","metadata":{"resourceVersion":"377360","selfLink":"/api/v1/services"}}
```

**Comment by vcozzolino** [comment]
@Poorunga I can run the command without problems:

```
$ curl 127.0.0.1:10550/api/v1/services
{"apiVersion":"v1","items":[{"apiVersion":"v1","kind":"Service","metadata":{"creationTimestamp":"2021-06-25T10:50:12Z","labels":{"component":"apiserver","provider":"kubernetes"},"managedFields":[{"apiVersion":"v1","fieldsType":"FieldsV1","fieldsV1":{"f:metadata":{"f:l ....
```

**Comment by Poorunga** [comment]
> But I also has the same problem with vcozzolino.

@vcozzolino You mean that edgemesh can work normally, but it will continuously print these error logs?

**Comment by EnfangCui** [comment]
> @EnfangCui You mean that edgemesh can work normally, but it will continuously print these error logs?

Yes, the URL can be resloved to IP address, but is also has these error logs. 
```
I0813 08:23:38.324377       1 dns.go:298] [EdgeMesh] dns server parse hostname-svc.default ip 10.98.167.255
```
What's more, I have another problem: 
```
root@edgenode:~# curl hostname-svc.default:12345
curl: (7) Failed to connect to hostname-svc.default port 12345: Connection timed out
```
I'll try to re-install edgemesh to see if this problem will happen again.

**Comment by Poorunga** [comment]
@EnfangCui  Please copy more edgemesh log for me, after you execute `curl -v hostname-svc.default:12345`

**Comment by EnfangCui** [comment]
@Poorunga Thank you very much. I solved this problem. I configure the **subnet** in 03-configmap.yaml to the service cluster IP range value of Kube apiserver. The range value can be found in **/etc/kubernetes/manifests/kube-apiserver.yaml**.

**Comment by Poorunga** [comment]
@vcozzolino You can also check whether it is a **subNet** setting problem. Refer to release-1.7 **readme**:
```
# Please set the subNet to the value of service-cluster-ip-range of kube-apiserver.
# You can obtain the value from the /etc/kubernetes/manifests/kube-apiserver.yaml file on the master node
$ kubectl apply -f build/kubernetes/edgemesh/03-configmap.yaml
configmap/edgemesh-cfg created
$ kubectl apply -f build/kubernetes/edgemesh/04-daemonset.yaml
daemonset.apps/edgemesh created
```
You also can try `kubectl cluster-info dump | grep "service-cluster-ip-range"` to obtain subNet. 
Then update the **subNet** field of the configmap/edgemesh-cfg and redeploy edgemesh.

If edgemesh still does not work, please tell me what happened :)

**Comment by vcozzolino** [comment]
After changing the subnet field in the YAML file, I can see that some DNS entries are appearing in the edgemesh agent logs:
```
I0816 07:11:26.996115       1 serviceproxy.go:200] [EdgeMesh] get cluster ip `10.96.0.10` --> kube-system.kube-dns
I0816 07:11:26.996129       1 serviceproxy.go:200] [EdgeMesh] get cluster ip `10.97.233.232` --> sedna.kb
I0816 07:11:26.996133       1 serviceproxy.go:200] [EdgeMesh] get cluster ip `10.96.0.1` --> default.kubernetes
I0816 07:11:26.996137       1 serviceproxy.go:200] [EdgeMesh] get cluster ip `10.99.155.129` --> monitoring.prometheus
I0816 07:11:26.996140       1 serviceproxy.go:200] [EdgeMesh] get cluster ip `10.107.217.124` --> default.containers-tracking-service-gnps5
I0816 07:11:26.996143       1 serviceproxy.go:200] [EdgeMesh] get cluster ip `10.106.219.177` --> default.pedestrian-tracking-service-mlfqm
I0816 07:11:26.996151       1 serviceproxy.go:200] [EdgeMesh] get cluster ip `10.108.136.163` --> hivemq.hivemq-operator
I0816 07:11:26.996155       1 serviceproxy.go:200] [EdgeMesh] get cluster ip `None` --> hivemq.hivemq-hivemq-cluster1-cluster
I0816 07:11:26.996159       1 serviceproxy.go:200] [EdgeMesh] get cluster ip `10.101.93.52` --> hivemq.hivemq-hivemq-cluster1-mqtt
I0816 07:11:26.996162       1 serviceproxy.go:200] [EdgeMesh] get cluster ip `10.98.59.83` --> hivemq.hivemq-hivemq-cluster1-cc
I0816 07:11:26.996166       1 serviceproxy.go:200] [EdgeMesh] get cluster ip `10.110.216.247` --> kubeedge.hostname-svc
I0816 07:11:26.996169       1 serviceproxy.go:200] [EdgeMesh] get cluster ip `10.108.128.204` --> default.pedestrian-tracking-service-pnbd2
I0816 07:11:26.997230       1 trace.go:205] Trace[276822101]: "Reflector ListAndWatch" name:istio.io/client-go/pkg/informers/externalversions/factory.gen.go:116 (16-Aug-2021 07:11:16.986) (total time: 10010ms):
Trace[276822101]: [10.010553244s] [10.010553244s] END
E0816 07:11:26.997252       1 reflector.go:127] istio.io/client-go/pkg/informers/externalversions/factory.gen.go:116: Failed to watch *v1alpha3.VirtualService: failed to list *v1alpha3.VirtualService: no kind "VirtualservicList" is registered for version "networking.istio.io/v1alpha3" in scheme "istio.io/client-go/pkg/clientset/versioned/scheme/register.gen.go:30"
E0816 07:11:26.997302       1 proxier.go:146] [EdgeMesh] open file /run/edgemesh-iptables err: open /run/edgemesh-iptables: no such file or directory
I0816 07:11:27.000057       1 trace.go:205] Trace[1182872406]: "Reflector ListAndWatch" name:k8s.io/client-go/informers/factory.go:134 (16-Aug-2021 07:11:16.985) (total time: 10014ms):
Trace[1182872406]: ---"Objects listed" 10014ms (07:11:00.999)
```

However, the DNS resolution still doesn't work but I think that it might not be related to edgemesh. I'm running some sanity checks on the cluster to see if there is something broken with kube-dns.

**Comment by Poorunga** [comment]
@vcozzolino What is your KubeEdge version and K8s version? Maybe it would be better for us to discuss your trouble in a new ISSUE topic :)

**Comment by vcozzolino** [comment]
> @vcozzolino What is your KubeEdge version and K8s version? Maybe it would be better for us to discuss your trouble in a new ISSUE topic :)

Yes, I will create a new issue. Things are looking better now because the `dig` command returns an answer when I try to resolve hostname-svc.kubeedge but I still see too many errors in the edgemesh agent logs.

**Comment by Poorunga** [comment]
> I still see too many errors in the edgemesh agent logs.

@vcozzolino The lower version of KubeEdge (<1.7.0) may have some bug, you can refer to: https://github.com/kubeedge/kubeedge/issues/2769

**Comment by vcozzolino** [comment]
The problem is now solved also on my side. I had to stop cloudcore and edgecore, remove my edgemesh-gateway deployments and, especially, delete all the kubeedge objectsync entries in my cluster ( I had more than 1k). After that, everything started working normally.
